### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by davglass** [gotwarlost/istanbul#13]
My `istanbul cover` commands fail on windows, but the `vows --spec ./test/foo.js` works fine.

I get this error:

```

YUI@WINDOWS7 ~/Desktop/play/cpr (master)
$ npm test

> cpr@0.0.5 pretest c:\Users\YUI\Desktop\play\cpr
> jshint --config ./node_modules/yui-lint/jshint.json ./lib/


> cpr@0.0.5 test c:\Users\YUI\Desktop\play\cpr
> istanbul cover --print both -- vows --spec ./tests/full.js


c:\Users\YUI\Desktop\play\cpr\node_modules\.bin\vows.CMD:1
(function (exports, require, module, __filename, __dirname) { :: Created by np
                                                              ^
Unexpected token :
SyntaxError: Unexpected token :
    at Module._compile (module.js:437:25)
    at Module._extensions..js (module.js:467:10)
    at Object.Module._extensions..js (c:\Users\YUI\Desktop\play\cpr\node_modules
\istanbul\lib\hook.js:101:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:492:10)
    at runFn (c:\Users\YUI\Desktop\play\cpr\node_modules\istanbul\lib\command\co
mmon\run-with-cover.js:80:16)
    at c:\Users\YUI\Desktop\play\cpr\node_modules\istanbul\lib\command\common\ru
n-with-cover.js:148:17
    at c:\Users\YUI\Desktop\play\cpr\node_modules\istanbul\lib\util\file-matcher
.js:52:16
    at c:\Users\YUI\Desktop\play\cpr\node_modules\istanbul\lib\util\file-matcher
.js:35:9
No coverage information was collected, exit without writing coverage information

npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

YUI@WINDOWS7 ~/Desktop/play/cpr (master)
$
```

For reference, that vows is running:

```

YUI@WINDOWS7 ~/Desktop/play/cpr (master)
$ ./node_modules/.bin/vows --spec ./tests/full.js

  ♢ CPR Tests

  should be loaded
    ✓ should have cpr method
  should fail on non-existant from dir
    ✓ should return an error in the callback
  should be loaded and should NOT copy node_modules
    ✓ does not have ./out/1
    ✓ and threw an error
  should be loaded and should not copy graceful-fs from function
    ✓ and has ./out/3
    ✓ and dirs are not equal
    ✓ and from directory has graceful-fs dir
    ✓ and to directory does not have graceful-fs dir
  should be loaded and should copy node_modules
    ✓ has ./out/0
    ✓ and dirs are equal
    ✓ and from directory has graceful-fs dir
    ✓ and to directory has graceful-fs dir
  should be loaded and should not copy yui-lint from regex
    ✓ and has ./out/2
    ✓ and dirs are not equal
    ✓ and from directory has yui-lint dir
    ✓ and to directory does not have yui-lint dir
  should be loaded and should copy node_modules with overwrite flag
    ✓ has ./out/0
    ✓ and dirs are equal
    ✓ and from directory has graceful-fs dir
    ✓ and to directory has graceful-fs dir

✓ OK » 20 honored (10.885s)


YUI@WINDOWS7 ~/Desktop/play/cpr (master)
$
```

**Comment by abhisekroy2002** [comment]
I am using this command 
istanbul cover C:\\Users\\abhisek.user\\AppData\\Roaming\\npm\\node_modules\\mocha\\bin\\_mocha test
But it is giving this as out put and not generating the report.
Transformation error; return original code
[TypeError: Object #<Object> has no method 'isIdentifierPart']
//
//
No coverage information was collected, exit without writing coverage information

**Comment by gotwarlost** [comment]
That seems to be an error in parsing your Javascript. Are you sure it is well-formed?

**Comment by abhisekroy2002** [comment]
Yes it is well formed. will be a reasonfir nide.js?

**Comment by alvin-milton** [comment]
Using latest version of karma... 

cmi-alvinmilton-1089-mbp:ng-desc-tests alvin.milton$ istanbul cover test/*-spec.js
No coverage information was collected, exit without writing coverage information
/Users/alvin.milton/Development/ng-desc-tests/test/add-spec.js:7

describe('add', function () {
^

ReferenceError: describe is not defined

```describe('add', function () {
  var add;
  beforeEach(function () {...```

**Comment by deltreey** [comment]
I can confirm that this is still an issue on windows 10.

```bash
C:\Program Files (x86)\nodejs\npm.CMD:1
(function (exports, require, module, __filename, __dirname) { :: Created by npm, please don't edit manually.
                                                              ^

SyntaxError: Unexpected token :
...
```

I am running it this way (without flags for readability):
```bash
istanbul cover npm run test:server
```

Please understand that this command works fine
```bash
npm run test:server
```

So there is no "magic" expansion of variables and I have no idea what you mean by that.

Technical details:
```bash
$ node -v
v5.1.1
$ npm -v
3.5.1
$ cat package.json | grep istanbul
    "istanbul": "0.3.17",
$ cat package.json | grep mocha
    "mocha": "2.3.3",
```

**Comment by deltreey** [comment]
I tested and can confirm that it persists in istanbul `0.4.1`

**Comment by centigrade-thomas-becker** [comment]
I have a similiar problem in Windows 8. This does not work:

`istanbul cover jasmine-node spec`

> No coverage information was collected, exit without writing coverage information
> C:\Users\x\AppData\Roaming\npm\jasmine-node.CMD:1
> (function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
>                                                               ^
> 
> SyntaxError: Unexpected token ILLEGAL
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\x\AppData\Roaming\npm\node_modules\istanbul\lib\hook.js:109:37)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
>     at runFn (C:\Users\x\AppData\Roaming\npm\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
>     at C:\Users\x\AppData\Roaming\npm\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17
>     at C:\Users\x\AppData\Roaming\npm\node_modules\istanbul\lib\util\file-matcher.js:68:16
> 

But if I add the path to the jasmine executable it works:

`istanbul cover node_modules\jasmine-node\bin\jasmine-node spec`

> ....
> 
> Finished in 12.51 seconds
> 4 tests, 7 assertions, 0 failures, 0 skipped

**Comment by scott-plutovr** [comment]
This is still an issue for me on Windows 10 using git-bash from git for Windows 2.8.3 from [1]. 
```
$ istanbul cover _mocha -- --recursive
No coverage information was collected, exit without writing coverage information
C:\Users\scott\AppData\Roaming\npm\_mocha.CMD:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\scott\AppData\Roaming\npm\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at runFn (C:\Users\scott\AppData\Roaming\npm\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
    at C:\Users\scott\AppData\Roaming\npm\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17
    at C:\Users\scott\AppData\Roaming\npm\node_modules\istanbul\lib\util\file-matcher.js:68:16
```
but if I pass the full path to _mocha it works,
```$ istanbul cover node_modules/mocha/bin/_mocha -- --recursive```

Here are some details of what is installed on my system:
```
$ istanbul help 2>&1 |grep version
istanbul version:0.4.3
```

```
$ node -v
v4.4.4
```

```
$ npm --version
2.15.1
```

```
$ mocha --version
2.4.5
```

Could it be due to previously ```npm install -g mocha``` and ```npm install -g istanbul``` ? The failing call stack is referencing the %APPDATA% paths of mocha and istanbul so maybe that is what is messed up?

```
$ where mocha
C:\Users\scott\AppData\Roaming\npm\mocha
C:\Users\scott\AppData\Roaming\npm\mocha.cmd
```

```
$ ls /c/Users/scott/AppData/Roaming/npm/node_modules/mocha/bin/
_mocha*  mocha*  options.js
```

```
$ where istanbul
C:\Users\scott\AppData\Roaming\npm\istanbul
C:\Users\scott\AppData\Roaming\npm\istanbul.cmd
```

```
$ where _mocha
C:\Users\scott\AppData\Roaming\npm\_mocha
C:\Users\scott\AppData\Roaming\npm\_mocha.cmd
```

```
$ ls ./node_modules/mocha/
bin/          images/   lib/     mocha.css  node_modules/
CHANGELOG.md  index.js  LICENSE  mocha.js   package.json
```

```
$ ls ./node_modules/istanbul/
CHANGELOG.md  index.js  lib/  LICENSE  node_modules/  package.json  README.md
```

```
$ istanbul cover -v _mocha -- --recursive
Using configuration
-------------------
verbose: true
instrumentation:
    root: .
    extensions:
        - .js
    default-excludes: true
    excludes: []
    embed-source: false
    variable: __coverage__
    compact: true
    preserve-comments: false
    complete-copy: false
    save-baseline: false
    baseline-file: ./coverage/coverage-baseline.json
    include-all-sources: false
    include-pid: false
    es-modules: false
    preload-sources: false
reporting:
    print: summary
    reports:
        - lcov
    dir: ./coverage
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
    report-config:
        clover: {file: clover.xml}
        cobertura: {file: cobertura-coverage.xml}
        json: {file: coverage-final.json}
        json-summary: {file: coverage-summary.json}
        lcovonly: {file: lcov.info}
        teamcity: {file: null, blockName: Code Coverage Summary}
        text: {file: null, maxCols: 0}
        text-lcov: {file: lcov.info}
        text-summary: {file: null}
hooks:
    hook-run-in-context: false
    post-require-hook: null
    handle-sigint: false
check:
    global:
        statements: 0
        lines: 0
        branches: 0
        functions: 0
        excludes: []
    each:
        statements: 0
        lines: 0
        branches: 0
        functions: 0
        excludes: []

-------------------

Running: node C:\Users\scott\AppData\Roaming\npm\_mocha.CMD --recursive
No coverage information was collected, exit without writing coverage information
C:\Users\scott\AppData\Roaming\npm\_mocha.CMD:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\scott\AppData\Roaming\npm\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at runFn (C:\Users\scott\AppData\Roaming\npm\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
    at C:\Users\scott\AppData\Roaming\npm\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17
    at C:\Users\scott\AppData\Roaming\npm\node_modules\istanbul\lib\util\file-matcher.js:68:16
```

```
$ cat /c/Users/scott/AppData/Roaming/npm/_mocha.cmd
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\node_modules\mocha\bin\_mocha" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\node_modules\mocha\bin\_mocha" %*
)
```

```
$ cat /c/Users/scott/AppData/Roaming/npm/_mocha
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/mocha/bin/_mocha" "$@"
  ret=$?
else
  node  "$basedir/node_modules/mocha/bin/_mocha" "$@"
  ret=$?
fi
exit $ret
```

```
$ uname
MINGW64_NT-10.0
```

Let me know if gathering any additional command output or file contents would be helpful.

**Comment by UziTech** [comment]
Still an issue with 
```
istanbul cover mocha
``` 
but 
```
istanbul cover node_modules/mocha/bin/_mocha
```
 works

**Comment by hausenism** [comment]
node -v

`v6.2.2`

npm -v

`3.9.5`

use istanbul as devDependencies.  used script:

`istanbul cover -x *.test.js node_modules/mocha/bin/_mocha -- -R spec src/index.test.js`

it works!

**Comment by fruch** [comment]
same as @scott-plutovr I alse see this error under git-bash

**Comment by DanielRuf** [comment]
Still relevant.

**Comment by ccoenen** [comment]
I also have this issue with node 10.1.0 on a windows machine.

**Comment by DanielRuf** [comment]
I guess we should setup appveyor and try to find solutions.

**Comment by aspencerpsu** [comment]
It seems like this is working for node versions 6 and 8, but it doesn't work for node version 10. I had to uninstall 10.15.3 and revert back to 8.15.1.

**Comment by DanielRuf** [comment]
> It seems like this is working for node versions 6 and 8, but it doesn't work for node version 10. I had to uninstall 10.15.3 and revert back to 8.15.1.

You can use nvm and alternatives to switch versions.

**Comment by aspencerpsu** [comment]
> > It seems like this is working for node versions 6 and 8, but it doesn't work for node version 10. I had to uninstall 10.15.3 and revert back to 8.15.1.
> 
> You can use nvm and alternatives to switch versions.

NVM doesn't work for me on an x64 Windows 10 system. I'm noticing there's no stdout when I'm running my coverage combined with _mocha.

`node ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha --harmony -- -R spec`

produces the coverage results without outputting the describe and it blocks during testing.

**Comment by DanielRuf** [comment]
> and alternatives

I did not say that nvm can be used on Windows (in general).

**Comment by UziTech** [comment]
you could use `npx node@8` to use node version 8 even when you have a different version installed

something like:

```sh
npx node@8 node_modules/istanbul/lib/cli.js cover *.test.js node_modules/mocha/bin/_mocha
```

**Comment by DanielRuf** [comment]
On WSL and Git Bash much more solutions should work.

**Comment by ccoenen** [comment]
WSL is not Windows either.

**Comment by DanielRuf** [comment]
> Damn, I wish I had an easy way to reproduce windows issues. Do you have a VM or something I can use to play with this.
> 
> Windows is the biggest gap in tests for istanbul

We can test with Travis CI.
I will open a PR for this.

**Comment by UziTech** [comment]
@DanielRuf I don't think this repo is maintained.

According to the readme:

> *Deprecation Notice:* this version of _istanbul_ is deprecated, we will not be
  landing pull requests or releasing new versions. But don't worry, the [Istanbul 2.0
  API is now available](https://istanbul.js.org/) and is being actively developed
  in the new [istanbuljs organization](https://github.com/istanbuljs).

**Comment by DanielRuf** [comment]
https://github.com/gotwarlost/istanbul/pull/910

But I think it is better to use another code coverage solution (v8 internally provides this already).

The last (tagged) release was in 2016 and last commit in 2017:
https://github.com/gotwarlost/istanbul/releases.

> According to the readme:
> 
> > _Deprecation Notice:_ this version of _istanbul_ is deprecated, we will not be
> > landing pull requests or releasing new versions. But don't worry, the [Istanbul 2.0
> > API is now available](https://istanbul.js.org/) and is being actively developed
> > in the new [istanbuljs organization](https://github.com/istanbuljs).

Right, time to migrate then I guess. Was not clear enough in the readme.

**Comment by DanielRuf** [comment]
https://github.com/istanbuljs/nyc it is then.

**Comment by SirPhemmiey** [comment]
If you're having this issue and you're on a Windows machine, all you need to do is to specify the full path of mocha to istanbul like so; 
`istanbul cover node_modules/mocha/bin/_mocha`
