### ISSUE TITLE
Module loading introduces very long stack trace

### ISSUE THREAD

**Issue by Raynos** [gotwarlost/istanbul#328]
```js
module.js:340
    throw err;
    ^
Error: Cannot find module './lib/alloc-cluster.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/raynos/uber/autobahn/test/register/exit-register.js:3:20)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.Module._extensions..js (/home/raynos/uber/autobahn/node_modules/istanbul/lib/hook.js:101:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/raynos/uber/autobahn/test/register/index.js:10:1)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.Module._extensions..js (/home/raynos/uber/autobahn/node_modules/istanbul/lib/hook.js:101:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/raynos/uber/autobahn/test/index.js:11:1)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.Module._extensions..js (/home/raynos/uber/autobahn/node_modules/istanbul/lib/hook.js:101:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at runFn (/home/raynos/uber/autobahn/node_modules/istanbul/lib/command/common/run-with-cover.js:116:16)
    at /home/raynos/uber/autobahn/node_modules/istanbul/lib/command/common/run-with-cover.js:240:17
    at /home/raynos/uber/autobahn/node_modules/istanbul/lib/util/file-matcher.js:56:16
    at /home/raynos/uber/autobahn/node_modules/istanbul/lib/util/file-matcher.js:35:9
    at Object.next (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/lib/fileset.js:41:14)
    at Fileset.emit (events.js:95:17)
    at Fileset.next (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:343:12)
    at Fileset.Glob._processEmitQueue (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:310:12)
    at Fileset.Glob.emitMatch (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:290:8)
    at Fileset.Glob._finish (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:230:8)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:183:27)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:450:14)
    at Fileset.Glob._afterReaddir (/home/raynos/uber/autobahn/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:695:17)
    at Object.oncomplete (fs.js:107:15)
```

When I run my tests with istanbul and I make a mistake with `require`, i.e. load a non-existant file the stack trace is incredibly long.

There are a log of `FileSet` frames in my stack that I really don't care about.

If we add a `process.nextTick` at the right place we can cut a lot of weight out of this stack trace.

**Comment by gotwarlost** [comment]
Where would you add it? The whole `require` processing is synchronous

**Comment by Raynos** [comment]
```
    at runFn (/home/raynos/uber/autobahn/node_modules/istanbul/lib/command/common/run-with-cover.js:116:16)
```

You can wrap ( https://github.com/gotwarlost/istanbul/blob/master/lib/command/common/run-with-cover.js#L120 ) in a nextTick.

**Comment by davglass** [comment]
@Raynos Do you have a repro case I can add? I did a couple of quick tests locally but couldn't get it to show that massive stack trace. I'll happily write the patch and add the test once I know what I'm looking at :)

**Comment by Raynos** [comment]
With version 0.3.x of istanbul I get

```
Error: Cannot find module 'fs2'
    at Function._resolveFilename (module.js:338:15)
    at Function._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/raynos/uber/autobahn/test/clients/heap-dumps.js:3:10)
    at Module._compile (module.js:456:26)
    at Object..js (module.js:474:10)
    at Object..js (/home/raynos/uber/autobahn/node_modules/istanbul/lib/hook.js:107:37)
    at Module.load (module.js:356:32)
    at Function._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/raynos/uber/autobahn/test/clients/index.js:6:1)
    at Module._compile (module.js:456:26)
    at Object..js (module.js:474:10)
    at Object..js (/home/raynos/uber/autobahn/node_modules/istanbul/lib/hook.js:107:37)
    at Module.load (module.js:356:32)
    at Function._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/raynos/uber/autobahn/test/index.js:14:1)
    at Module._compile (module.js:456:26)
    at Object..js (module.js:474:10)
    at Object..js (/home/raynos/uber/autobahn/node_modules/istanbul/lib/hook.js:107:37)
    at Module.load (module.js:356:32)
    at Function._load (module.js:312:12)
    at Function.runMain (module.js:497:10)
    at /home/raynos/uber/autobahn/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16
    at /home/raynos/uber/autobahn/node_modules/istanbul/lib/command/common/run-with-cover.js:248:17
    at /home/raynos/uber/autobahn/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /home/raynos/uber/autobahn/node_modules/async/lib/async.js:254:17
    at done (/home/raynos/uber/autobahn/node_modules/async/lib/async.js:135:19)
    at /home/raynos/uber/autobahn/node_modules/async/lib/async.js:32:16
    at /home/raynos/uber/autobahn/node_modules/async/lib/async.js:251:21
    at LOOP (fs.js:1369:14)
    at process._tickCallback (node.js:419:13)
```

Looks like someone already added a net tick somewhere :)
