### ISSUE TITLE
Did the karma fork get merged upstream?

### ISSUE THREAD

**Issue by lukescott** [gotwarlost/istanbul#350]
I'm trying karma coverage 0.3.1. I thought the PR got merged. I'm getting the following error:

```
ERROR [coverage]: [TypeError: Cannot read property 'split' of undefined]
TypeError: Cannot read property 'split' of undefined
    at HtmlReport.Report.mix.writeDetailPage (/Users/lukescott/Documents/Projects/webconnex/director-js/node_modules/istanbul/lib/report/html.js:395:30)
    at /Users/lukescott/Documents/Projects/webconnex/director-js/node_modules/istanbul/lib/report/html.js:472:26
    at SyncFileWriter.extend.writeFile (/Users/lukescott/Documents/Projects/webconnex/director-js/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.extend.writeFile (/Users/lukescott/Documents/Projects/webconnex/director-js/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /Users/lukescott/Documents/Projects/webconnex/director-js/node_modules/istanbul/lib/report/html.js:471:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (/Users/lukescott/Documents/Projects/webconnex/director-js/node_modules/istanbul/lib/report/html.js:465:23)
    at /Users/lukescott/Documents/Projects/webconnex/director-js/node_modules/istanbul/lib/report/html.js:467:22
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (/Users/lukescott/Documents/Projects/webconnex/director-js/node_modules/istanbul/lib/report/html.js:465:23)
```

It works with the fork though.

**Comment by davglass** [comment]
I'm new to helping with the project, can you specify which PR needed to be merged and how I can test this?

**Comment by lukescott** [comment]
@davglass Sorry for the confusion! This was meant for isparta. Multi-tasking fail...
