### ISSUE TITLE
Inscrutable errors when running with jasmine-node

### ISSUE THREAD

**Issue by danascheider** [gotwarlost/istanbul#406]
I'm using Istanbul with Jasmine-Node, using the command `npm test`, which is configured to call<pre><code>istanbul cover  --include-all-sources jasmine-node -- --forceexit spec</code></pre>The test suite runs, but at the end, it crashes with this error:<pre><code>/var/www/node_modules/istanbul/node_modules/esprima/esprima.js:5446
            throw e;
                  ^
Error: Line 19: Unexpected token ,
    at createError (/var/www/node_modules/istanbul/node_modules/esprima/esprima.js:2327:21)
    at unexpectedTokenError (/var/www/node_modules/istanbul/node_modules/esprima/esprima.js:2402:13)
    at throwUnexpectedToken (/var/www/node_modules/istanbul/node_modules/esprima/esprima.js:2407:15)
    at parsePrimaryExpression (/var/www/node_modules/istanbul/node_modules/esprima/esprima.js:3184:13)
    at inheritCoverGrammar (/var/www/node_modules/istanbul/node_modules/esprima/esprima.js:2583:18)
    at parseLeftHandSideExpressionAllowCall (/var/www/node_modules/istanbul/node_modules/esprima/esprima.js:3275:20)
    at inheritCoverGrammar (/var/www/node_modules/istanbul/node_modules/esprima/esprima.js:2583:18)
    at parsePostfixExpression (/var/www/node_modules/istanbul/node_modules/esprima/esprima.js:3349:16)
    at parseUnaryExpression (/var/www/node_modules/istanbul/node_modules/esprima/esprima.js:3409:20)
    at inheritCoverGrammar (/var/www/node_modules/istanbul/node_modules/esprima/esprima.js:2583:18)
npm ERR! Test failed.  See above for more details.</code></pre>I am running Debian 7 with iojs 2.3.4 and jasmine-node 1.14.3.

I don't know if this is a bug or if I'm just doing something wrong, but thought I'd let you know it's happening. Unfortunately, my JavaScript capabilities are not at a point where I could make a PR but I thought you'd like to know.

**Comment by hyobyun** [comment]
I'm getting the same bug except, its on the semicolon:
Not sure what to make of it...

    C:\...\node_modules\istanbul\node_modules\esprima\esprima.js:5599
                throw e;
                      ^
    Error: Line 51: Unexpected token ;

**Comment by nilveryawesome** [comment]
+1 same error

**Comment by nilveryawesome** [comment]
```
istanbul/node_modules/esprima/esprima.js:5599
            throw e;
                  ^
Error: Line 1: Unexpected token
```

**Comment by davglass** [comment]
Can someone please attach some code that makes it generate this error? It's very hard to debug what we can't see :)

**Comment by hyobyun** [comment]
Apologize for the late response- I narrowed down the issue to a .js file with badly matched brackets. A file with one extra bracket staying open caused this error. Once we matched up the brackets, this error went away.

**Comment by prajeeshkayyur** [comment]
Same error...


`Finished in 1.046 seconds
127 tests, 195 assertions, 0 failures, 0 skipped


>> 
>> /usr/local/lib/node_modules/istanbul/node_modules/esprima/esprima.js:5701
>>             throw e;
>>                   ^
>> Error: Line 36: Unexpected token *
>>     at constructError (/usr/local/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2406:21)
>>     at createError (/usr/local/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2425:17)
>>     at unexpectedTokenError (/usr/local/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2499:13)
>>     at throwUnexpectedToken (/usr/local/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2504:15)
>>     at parsePrimaryExpression (/usr/local/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3306:13)
>>     at inheritCoverGrammar (/usr/local/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2680:18)
>>     at parseLeftHandSideExpressionAllowCall (/usr/local/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3413:20)
>>     at inheritCoverGrammar (/usr/local/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2680:18)
>>     at parsePostfixExpression (/usr/local/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3489:16)
>>     at parseUnaryExpression (/usr/local/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3549:20)
>>     at inheritCoverGrammar (/usr/local/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2680:18)
>>     at parseBinaryExpression (/usr/local/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3638:16)
>>     at inheritCoverGrammar (/usr/local/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2680:18)
>>     at parseConditionalExpression (/usr/local/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3695:16)
>>     at parseAssignmentExpression (/usr/local/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3892:16)
>>     at isolateCoverGrammar (/usr/local/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2662:18)
****************************************************
* One or more tests failed. Please check logs above! *
8
****************************************************
>> Exited with code: 1.
Warning: Task "exec:runcoverage" failed. Use --force to continue.

Aborted due to warnings.`

**Comment by crobinson42** [comment]
Same issue.. here's my code example:

`istanbul cover --include-all-sources jasmine-node test`

test/TestSpec.js:
```
describe("Hello world", function() {
  it("should respond with hello world", function(done) {
    expect("").toEqual("");
    done();
  });
});
```

**Comment by crobinson42** [comment]
Haha.. Bump! Bad bracket matching in the js file!

**Comment by crobinson42** [comment]
I resolved the issue in my code by removing a `require` statement at the top of my spec file.
