### ISSUE TITLE
ECMA6 Instrument issue

### ISSUE THREAD

**Issue by diegossilveira** [gotwarlost/istanbul#457]
Consider the following code written using ECMA 6 new classes syntax:

```javascript
// minimal.js
'use strict';

const events = require('events');

class Foo extends events.EventEmitter {

  constructor () {
    super();    
  }

}
```

When running `istanbul instrument minimal.js` I get this error:

```javascript
/Users/diegosilveira/.nvm/versions/node/v4.0.0/lib/node_modules/istanbul/node_modules/escodegen/escodegen.js:2407
        result = this[type](expr, precedence, flags);
                           ^

TypeError: this[type] is not a function
    at CodeGenerator.generateExpression (/Users/diegosilveira/.nvm/versions/node/v4.0.0/lib/node_modules/istanbul/node_modules/escodegen/escodegen.js:2407:28)
    at CodeGenerator.Expression.CallExpression (/Users/diegosilveira/.nvm/versions/node/v4.0.0/lib/node_modules/istanbul/node_modules/escodegen/escodegen.js:1854:28)
    at CodeGenerator.generateExpression (/Users/diegosilveira/.nvm/versions/node/v4.0.0/lib/node_modules/istanbul/node_modules/escodegen/escodegen.js:2407:28)
    at CodeGenerator.Statement.ExpressionStatement (/Users/diegosilveira/.nvm/versions/node/v4.0.0/lib/node_modules/istanbul/node_modules/escodegen/escodegen.js:1312:28)
    at CodeGenerator.generateStatement (/Users/diegosilveira/.nvm/versions/node/v4.0.0/lib/node_modules/istanbul/node_modules/escodegen/escodegen.js:2420:33)
    at /Users/diegosilveira/.nvm/versions/node/v4.0.0/lib/node_modules/istanbul/node_modules/escodegen/escodegen.js:1078:51
    at withIndent (/Users/diegosilveira/.nvm/versions/node/v4.0.0/lib/node_modules/istanbul/node_modules/escodegen/escodegen.js:582:9)
    at CodeGenerator.Statement.BlockStatement (/Users/diegosilveira/.nvm/versions/node/v4.0.0/lib/node_modules/istanbul/node_modules/escodegen/escodegen.js:1028:13)
    at CodeGenerator.generateStatement (/Users/diegosilveira/.nvm/versions/node/v4.0.0/lib/node_modules/istanbul/node_modules/escodegen/escodegen.js:2420:33)
    at CodeGenerator.maybeBlock (/Users/diegosilveira/.nvm/versions/node/v4.0.0/lib/node_modules/istanbul/node_modules/escodegen/escodegen.js:837:33)
```

**Comment by sterlinghw** [comment]
What version are you running? This appears to be related to:

#414 #455 #435

**Comment by diegossilveira** [comment]
I'm using istanbul v0.3.19

**Comment by gotwarlost** [comment]
could you try with the latest version - I believe the `super` issue was fixed by one of the PRs merged recently

**Comment by sterlinghw** [comment]
@diegossilveira 0.3.21does not work with super. Update to 0.3.22 to gain support.
