### ISSUE TITLE
Error Stacks showing line number 9 instead of the correct line number

### ISSUE THREAD

**Issue by kevinawoo** [gotwarlost/istanbul#458]
When running 
```bash
NODE_ENV=test istanbul cover ----include-all-sources --report html _mocha -- --ui bdd --timeout 10000
```

I get call stacks without a usable line number and a very large column number.
`(modules/utils/Test/fixtures/User.js:9:1951)`
```
1) Breaking Test:
     Error: An Error has been thrown
      at endReadableNT (_stream_readable.js:889:12)
  From previous event:
      at createUser (modules/utils/Test/fixtures/User.js:9:1951)
      at modules/utils/Test/fixtures/User.js:9:16667
```

**Comment by mellema** [comment]
I'm seeing this too

**Comment by mgartner** [comment]
I'm seeing this too. Any ideas what is causing this?

**Comment by csulok** [comment]
See #274
