### ISSUE TITLE
Not able to include depended file from other folders/ Hard dependency on required files order

### ISSUE THREAD

**Issue by prajeeshkayyur** [gotwarlost/istanbul#524]
I have two folders( base, products). each folders having its source and specs files. base having all framework files , which is required to execute products source code.

I'm running istanbul code coverage from products,

grunt task~

prepare_code_coverage: {
                target: {
                    src: ['./products/**/*.js'],
                    options: {
                        //coverageFolder: 'lcov',
                        coverage: true,
                        noColors: true,
                        dryRun: false,
                        globals: false,
                        root: './base',
                        print: 'detail',
                        check: {
                            lines: 1
                        },
                        excludes: ['node_modules'],
                        mochaOptions: ['--bail', '--debug-brk'],
                        istanbulOptions: ['--default-excludes'],
                        reporter: 'spec',
                        reportFormats: ['lcovonly']
                    }
                }
            }

set root as './base' folder and running the above task from 'product' folder ~products$ grunt prepare_code_coverage

results shows errors. it says depended base folder files and depended object is not defined.

later i modifie the src to src: ['./base/core.js','./products/**/*.js']

this time it is expecting the second depended 'base' file.

For getting this code coverage successful I need to include each base file in same depended order , also these 'base' files executing for code coverage which is not required me( these all are depended files not instrument)

Is there any other way I can include bulk required files from different folder with out maintaining the order?

**Comment by gotwarlost** [comment]
Sorry, I don't understand your bug report. Could you provide a simple example repo on github that shows the core of the problem?

**Comment by prajeeshkayyur** [comment]
https://github.com/imvetri/istanbul-issue

Here is the sample code, I just created the folder structure and files are dummy....

When I'm running** grunt mocha_istanbul** I get below errors,


blr-valappip-m:product valappip$ grunt mocha_istanbul
Running "mocha_istanbul:target" (mocha_istanbul) task
=============================================================================
Writing coverage object [/Users/valappip/Documents/sample/Project/product/coverage/coverage.json]
Writing coverage reports at [/Users/valappip/Documents/sample/Project/product/coverage]
=============================================================================
-------------|----------|----------|----------|----------|----------------|
File         |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------|----------|----------|----------|----------|----------------|
 product/    |    16.67 |        0 |        0 |    16.67 |                |
  product.js |    16.67 |        0 |        0 |    16.67 |      3,4,5,8,9 |
-------------|----------|----------|----------|----------|----------------|
All files    |    16.67 |        0 |        0 |    16.67 |                |
-------------|----------|----------|----------|----------|----------------|


/Users/valappip/Documents/sample/Project/product/product.js:9
+;__cov_EAW2yb3R5F_Tsrw2MYoQSg.s['6']++;return this.productName;};}(window.Bas
                                                                    ^
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/valappip/Documents/sample/Project/product/product.js:9:605)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/valappip/Documents/sample/Project/product/node_modules/istanbul/lib/hook.js:107:24)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/valappip/Documents/sample/Project/product/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/valappip/Documents/sample/Project/product/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/Users/valappip/Documents/sample/Project/product/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/Users/valappip/Documents/sample/Project/product/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/valappip/Documents/sample/Project/product/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at runFn (/Users/valappip/Documents/sample/Project/product/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at /Users/valappip/Documents/sample/Project/product/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at /Users/valappip/Documents/sample/Project/product/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /Users/valappip/Documents/sample/Project/product/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at /Users/valappip/Documents/sample/Project/product/node_modules/istanbul/node_modules/async/lib/async.js:361:13
    at /Users/valappip/Documents/sample/Project/product/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at done (/Users/valappip/Documents/sample/Project/product/node_modules/istanbul/node_modules/async/lib/async.js:246:17)
    at /Users/valappip/Documents/sample/Project/product/node_modules/istanbul/node_modules/async/lib/async.js:44:16
    at /Users/valappip/Documents/sample/Project/product/node_modules/istanbul/node_modules/async/lib/async.js:358:17
    at LOOP (fs.js:1356:14)
    at process._tickCallback (node.js:415:13)
>> 
Warning: Task "mocha_istanbul:target" failed. Use --force to continue.

Aborted due to warnings.



After passing the window object it will say ... Base undefined

How can I execute code coverage for all files under product folder with some other folders/files depended ?

Thanks,
P

**Comment by prajeeshkayyur** [comment]
@gotwarlost , Any update on this ? It would be very helpful if you give any hint on this....

**Comment by prajeeshkayyur** [comment]
@gotwarlost 

https://github.com/imvetri/JS-coverage

Here is the better example of the issue what I'm facing.


configurations I'm given 
files: [
        'base/*.js',
        'src/*.js'
      'test/spec/*.js',
    ],


and npm test gives below error

> coverage-jasmine-istanbul-karma@0.0.1 test /Users/valappip/Downloads/coverage-jasmine-istanbul-karma-master
> node_modules/.bin/karma start my.conf.js

INFO [karma]: Karma v0.10.10 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X)]: Connected on socket 70e_eJb6AVI-1iy4f_F9
PhantomJS 1.9.8 (Mac OS X) ERROR
	ReferenceError: Can't find variable: base
	at /Users/valappip/Downloads/coverage-jasmine-istanbul-karma-master/base/base-base.js:6
PhantomJS 1.9.8 (Mac OS X): Executed 0 of 0 ERROR (0.03 secs / 0 secs)
npm ERR! weird error 1
npm ERR! not ok code 0


if I give the files with order then it works and generating the reports,

files: [
        'base/base.js',
        'base/base-base.js',
        'src/*.js'
      'test/spec/*.js',
    ],


But in my projects there are lots of files, So cant add one by one files in config.

Is order of files hardly depended? or How can I include these depended files before test starts?

Thanks,
P
