### ISSUE TITLE
Error on HTML Report generation

### ISSUE THREAD

**Issue by tommeier** [gotwarlost/istanbul#56]
Hi,

I've found some odd behaviour in generating the reports. Text and Text-Summary work perfectly.

Running result set over text-summary:

```
Using reporter [text-summary]

=============================== Coverage summary ===============================
Statements   : 89.36% ( 3803/4256 )
Branches     : 69.23% ( 333/481 )
Functions    : 86.9% ( 418/481 )
Lines        : 98.06% ( 152/155 )
================================================================================
Done
```

Same for HTML :

```
Using reporter [html]
Done

/folder/location/node_modules/istanbul/lib/report/html.js:252
                startCol = meta.start.column;
                               ^
TypeError: Cannot read property 'start' of undefined
    at /folder/location/node_modules/istanbul/lib/report/html.js:252:32
    at Array.forEach (native)
    at annotateBranches (/folder/location/node_modules/istanbul/lib/report/html.js:230:30)
    at HtmlReport.Report.mix.writeDetailPage (/folder/location/node_modules/istanbul/lib/report/html.js:374:9)
    at Report.mix.writeFiles (/folder/location/node_modules/istanbul/lib/report/html.js:436:26)
    at AsyncFileWriter.extend.processFile (/folder/location/node_modules/istanbul/lib/util/file-writer.js:93:9)
    at async.queue.q.process (/folder/location/node_modules/istanbul/node_modules/async/lib/async.js:725:21)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

```

Have you seen anything like this before?

The only way I could get around this, and the coverage data still looks correct, is by updating the specific html.js file to handle no `metaData` attribute:

Updating the `html.js` file from this (line 246):

```
        if (sumCount > 0) { //only highlight if partial branches are missing
            for (i = 0; i < branchArray.length; i += 1) {
                count = branchArray[i];
                meta = metaArray[i];
                type = count > 0 ? 'yes' : 'no';

```

to this:

```
        if (sumCount > 0) { //only highlight if partial branches are missing
            for (i = 0; i < branchArray.length **&& metaArray[i]**; i += 1) {
                count = branchArray[i];
                meta = metaArray[i];
                type = count > 0 ? 'yes' : 'no';

```

(Haven't done it in a pull request, as i really have no idea if its a valid bug or not)

Cheers,

Tom

**Comment by adjavaherian** [comment]
Is it possible that this is the same issue?

`
15 12 2015 16:25:50.220:ERROR [coverage]: [TypeError: Cannot read property 'start' of undefined]
TypeError: Cannot read property 'start' of undefined
    at /home/adjavaherian/Desktop/web-off-master/node_modules/istanbul/lib/object-utils.js:59:44
    at Array.forEach (native)
    at Object.addDerivedInfoForFile (/home/adjavaherian/Desktop/web-off-master/node_modules/istanbul/lib/object-utils.js:58:37)
    at Object.Collector.fileCoverageFor (/home/adjavaherian/Desktop/web-off-master/node_modules/istanbul/lib/collector.js:94:15)
    at /home/adjavaherian/Desktop/web-off-master/node_modules/istanbul/lib/report/html.js:558:90
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeReport (/home/adjavaherian/Desktop/web-off-master/node_modules/istanbul/lib/report/html.js:557:27)
    at writeReport (/home/adjavaherian/Desktop/web-off-master/node_modules/karma-coverage/lib/reporter.js:62:16)
    at /home/adjavaherian/Desktop/web-off-master/node_modules/karma-coverage/lib/reporter.js:288:11
    at /home/adjavaherian/Desktop/web-off-master/node_modules/karma/lib/helper.js:82:7
    at FSReqWrap.oncomplete (fs.js:82:15)

`
