### ISSUE TITLE
error report => 

### ISSUE THREAD

**Issue by ORESoftware** [gotwarlost/istanbul#595]
I got this just:

```
/usr/local/lib/node_modules/istanbul/lib/object-utils.js:110
                skipped = map && map[key].skip;
                                         ^

TypeError: Cannot read property 'skip' of undefined
    at /usr/local/lib/node_modules/istanbul/lib/object-utils.js:110:42
    at Array.forEach (native)
    at computeSimpleTotals (/usr/local/lib/node_modules/istanbul/lib/object-utils.js:108:28)
    at Object.summarizeFileCoverage (/usr/local/lib/node_modules/istanbul/lib/object-utils.js:215:25)
    at /usr/local/lib/node_modules/istanbul/lib/report/html.js:558:58
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeReport (/usr/local/lib/node_modules/istanbul/lib/report/html.js:557:27)
    at LcovReport.Report.mix.writeReport (/usr/local/lib/node_modules/istanbul/lib/report/lcov.js:55:19)
    at /usr/local/lib/node_modules/istanbul/lib/reporter.js:93:20
    at Array.forEach (native)

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

```

I got that by running this big command:

```
echo "istanbul cover /Users/amills001c/WebstormProjects/oresoftware/suman/test/build-tests/empty.js --dir ./coverage/#Users#amills001c#WebstormProjects#oresoftware#suman#test#build-tests#empty.js
istanbul cover /Users/amills001c/WebstormProjects/oresoftware/suman/test/build-tests/test6.js --dir ./coverage/#Users#amills001c#WebstormProjects#oresoftware#suman#test#build-tests#test6.js
istanbul cover /Users/amills001c/WebstormProjects/oresoftware/suman/test/build-tests/test7-start.js --dir ./coverage/#Users#amills001c#WebstormProjects#oresoftware#suman#test#build-tests#test7-start.js
istanbul cover /Users/amills001c/WebstormProjects/oresoftware/suman/test/build-tests/test8.js --dir ./coverage/#Users#amills001c#WebstormProjects#oresoftware#suman#test#build-tests#test8.js
istanbul cover /Users/amills001c/WebstormProjects/oresoftware/suman/test/build-tests/test9.js --dir ./coverage/#Users#amills001c#WebstormProjects#oresoftware#suman#test#build-tests#test9.js
istanbul report" | bash
```

I got the files under the coverage directory, so that part is successful:

<img width="712" alt="screenshot 2016-04-11 00 18 11" src="https://cloud.githubusercontent.com/assets/11139560/14419475/eb5f8bcc-ff7a-11e5-9008-9811e21ac759.png">

My guess is that the last portion of the command "istanbul report" is what failed.

Because when I run "istanbul report"  after getting the output in the coverage dir:

```
CACSVML-16845:suman amills001c$ istanbul report
/usr/local/lib/node_modules/istanbul/lib/object-utils.js:110
                skipped = map && map[key].skip;
                                         ^

TypeError: Cannot read property 'skip' of undefined
    at /usr/local/lib/node_modules/istanbul/lib/object-utils.js:110:42
    at Array.forEach (native)
    at computeSimpleTotals (/usr/local/lib/node_modules/istanbul/lib/object-utils.js:108:28)
    at Object.summarizeFileCoverage (/usr/local/lib/node_modules/istanbul/lib/object-utils.js:215:25)
    at /usr/local/lib/node_modules/istanbul/lib/report/html.js:558:58
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeReport (/usr/local/lib/node_modules/istanbul/lib/report/html.js:557:27)
    at LcovReport.Report.mix.writeReport (/usr/local/lib/node_modules/istanbul/lib/report/lcov.js:55:19)
    at /usr/local/lib/node_modules/istanbul/lib/reporter.js:93:20
    at Array.forEach (native)

```

**Comment by ORESoftware** [comment]
Perhaps I need more arguments to the "$ istanbul report" command, but I didn't see from the docs what to add to it. I am also not sure what the difference is between "$ istanbul report" vs "$ istanbul coverage".
I am just trying to follow the advice here:

https://github.com/gotwarlost/istanbul/issues/97

**Comment by ORESoftware** [comment]
I also got this one! Weird, what am I doing to break it? :+1: 

```
/usr/local/lib/node_modules/istanbul/lib/object-utils.js:59
                var line = statementMap[st].start.line,
                                           ^

TypeError: Cannot read property 'start' of undefined
    at /usr/local/lib/node_modules/istanbul/lib/object-utils.js:59:44
    at Array.forEach (native)
    at Object.addDerivedInfoForFile (/usr/local/lib/node_modules/istanbul/lib/object-utils.js:58:37)
    at Object.Collector.fileCoverageFor (/usr/local/lib/node_modules/istanbul/lib/collector.js:94:15)
    at /usr/local/lib/node_modules/istanbul/lib/report/html.js:558:90
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeReport (/usr/local/lib/node_modules/istanbul/lib/report/html.js:557:27)
    at LcovReport.Report.mix.writeReport (/usr/local/lib/node_modules/istanbul/lib/report/lcov.js:55:19)
    at /usr/local/lib/node_modules/istanbul/lib/reporter.js:93:20
    at Array.forEach (native)
```

**Comment by codekirei** [comment]
Try using the `--include` flag to point `istanbul report` at the coverage files you are generating.

`$ istanbul help report` for details.

I bet `report` is looking in the default location, not seeing any coverage files, and blowing up on you.

**Comment by ORESoftware** [comment]
thanks! actually I believe with 99% confidence that the errors I generated are due to **folder names inside the coverage folder that start with # (hash) or - (dash) characters.** I think these are legit chars to use for folder names, so maybe double check your code to see why those might cause problems? Once I removed those chars,  "$istanbul report" worked without errors at least. I will try out the --include flag.

Can you please please let me know how "$ istanbul report " works real quick? Does it go through all the directories specified by the --include option and concatenate the reports somehow into a big report?

**Comment by ORESoftware** [comment]
Also, I originally made the assumption that "$ istanbul report " would by default look through the coverage directory for any subdirectories? Is there a recursive option? It would be more convenient to do something like this:

`$ istanbul report -r ./coverage`

instead of doing

`$ istanbul report --include ./coverage/A ./coverage/B ./coverage/C`

hope that is correct and makes sense

**Comment by ORESoftware** [comment]
Ok so even then I get an error:

![screenshot 2016-04-11 14 31 22](https://cloud.githubusercontent.com/assets/11139560/14443112/18423c6c-fff2-11e5-8f6a-6bf7e19abee2.png)

In the screenshot you can see the directory structure

when I run this command:

`istanbul report --include coverage/test6 coverage/test8`

I get
```
/usr/local/lib/node_modules/istanbul/lib/reporter.js:58
            throw inputError.create('Invalid report format [' + fmt + ']');

Error: Invalid report format [./coverage/test8]
    at Object.module.exports.create (/usr/local/lib/node_modules/istanbul/lib/util/input-error.js:7:15)
    at Object.Reporter.add (/usr/local/lib/node_modules/istanbul/lib/reporter.js:58:30)
    at /usr/local/lib/node_modules/istanbul/lib/reporter.js:69:18
    at Array.forEach (native)
    at Object.Reporter.addAll (/usr/local/lib/node_modules/istanbul/lib/reporter.js:68:14)
    at ReportCommand.Command.mix.run (/usr/local/lib/node_modules/istanbul/lib/command/report.js:101:18)
    at runCommand (/usr/local/lib/node_modules/istanbul/lib/cli.js:83:19)
    at runToCompletion (/usr/local/lib/node_modules/istanbul/lib/cli.js:87:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/istanbul/lib/cli.js:93:5)
    at Module._compile (module.js:409:26)
```

Just to make sure I tried this too:

`$ istanbul report --include ./coverage/test6 ./coverage/test8`

same thing

**Comment by codekirei** [comment]
Just FYI, I'm in no way officially related to `istanbul` &mdash; I'm just another user (like you!) who happened to see this issue and suggested a potential fix based on my experience with using `istanbul` in my own projects :smile:

That said, your use case is divergent enough from what I usually do with `istanbul` that I'm not sure I can be much more helpful.

It is certainly interesting that omitting leading `#` and `-` chars from your coverage folder names fixes `report` &mdash; that almost feels like there's an escaping error somewhere. I might dig into the source later out of curiosity (time permitting), but no promises.

**Comment by ORESoftware** [comment]
ok well thanks :) do you happen to have any idea about this one ? https://github.com/gotwarlost/istanbul/issues/596

the # and - char issue is probably an edge case so hopefully the authors get to it but low priority
