### ISSUE TITLE
mocha and istanbul Unexpected reserved word and No coverage information was collected

### ISSUE THREAD

**Issue by lettfeti** [gotwarlost/istanbul#605]
I'm trying to use istanbul and am running into these two issues:

```
node_modules/react-google-charts/node_modules/scriptjs/dist/script.js:12
  var doc = document
            ^

ReferenceError: document is not defined
```

by running the test-script with  -x '**/node_modules/**/node_modules/**' i'm able to get further (i hope)

I'm getting the following error:
No coverage information was collected, exit without writing coverage information
(function (exports, require, module, __filename, __dirname) { import { expect } from 'chai'

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
...

It may be unrelated to istanbul, but i'm not finding solutions elsewhere.

package.json
`"scripts": {
    "test": "mocha --compilers js:babel-core/register --require ./frontend/js/test/test_helper.js --require ignore-styles --reporter mocha-junit-reporter --reporter-options mochaFile=./test-reports/mocha.xml 'frontend/js/test/**/*.@(js|jsx)'",
    "test:coverage": "babel-node ./node_modules/istanbul/lib/cli.js cover node_modules/mocha/bin/_mocha -- --recursive 'frontend/js/test/**/*.js'"
  }, 
"devDependencies": {
    "babel-cli": "^6.2.0",
    "babel-core": "^6.1.21",
    "babel-loader": "^6.2.0",
    "babel-polyfill": "^6.1.19",
    "babel-preset-es2015": "^6.1.4",
    "babel-preset-react": "^6.1.18",
    "babel-register": "^6.6.0",
    "...", "...",
    "istanbul": "^1.0.0-alpha.2",
    "jsdom": "^8.0.1",
    "sinon": "^1.17.3",
    "webpack": "^1.12.12"
// ...
"babel": {
    "presets": [
      "es2015",
      "react"
    ]
  }
`

**Comment by potapovDim** [comment]
@lettfeti 
"test": "babel-node ./node_modules/istanbul/lib/cli cover node_modules/mocha/bin/_mocha --  --bail --recursive"
