### ISSUE TITLE
Istanbul crashes after mocha tests ran

### ISSUE THREAD

**Issue by danieldiekmeier** [gotwarlost/istanbul#610]
I run my tests with

```
./node_modules/istanbul/lib/cli.js cover node_modules/mocha/bin/_mocha -- tests/*
```

and then I get an error. If I just run `mocha tests/*`, everything works. I tried reinstalling, but it didn't help. I'm running Node 5.11.0, but I also tried with 5.7.1. I tried using Istanbul 0.4.3 and 0.4.2.

This is the output I get:

```
/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:5701
            throw e;
            ^
Error: Line 1: Unexpected token
    at constructError (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:2406:21)
    at createError (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:2425:17)
    at unexpectedTokenError (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:2499:13)
    at tolerateUnexpectedToken (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:2508:21)
    at parseStatementListItem (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3967:21)
    at parseFunctionSourceElements (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:4868:23)
    at parseFunctionExpression (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:5073:16)
    at parsePrimaryExpression (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3272:24)
    at inheritCoverGrammar (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:2680:18)
    at parseLeftHandSideExpressionAllowCall (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3413:20)
    at inheritCoverGrammar (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:2680:18)
    at parsePostfixExpression (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3489:16)
    at parseUnaryExpression (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3549:20)
    at inheritCoverGrammar (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:2680:18)
    at parseBinaryExpression (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3638:16)
    at inheritCoverGrammar (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:2680:18)
    at parseConditionalExpression (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3695:16)
    at parseAssignmentExpression (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3892:16)
    at inheritCoverGrammar (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:2680:18)
    at parseGroupExpression (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3161:16)
    at inheritCoverGrammar (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:2680:18)
    at parsePrimaryExpression (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3238:20)
    at inheritCoverGrammar (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:2680:18)
    at parseLeftHandSideExpressionAllowCall (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3413:20)
    at inheritCoverGrammar (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:2680:18)
    at parsePostfixExpression (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3489:16)
    at parseUnaryExpression (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3549:20)
    at inheritCoverGrammar (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:2680:18)
    at parseBinaryExpression (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3638:16)
    at inheritCoverGrammar (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:2680:18)
    at parseConditionalExpression (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3695:16)
    at parseAssignmentExpression (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3892:16)
    at isolateCoverGrammar (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:2662:18)
    at parseExpression (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3941:16)
    at parseExpressionStatement (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:4221:20)
    at parseStatement (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:4759:24)
    at parseStatementListItem (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:3988:16)
    at parseScriptBody (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:5489:25)
    at parseProgram (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:5505:16)
    at Object.parse (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/node_modules/esprima/esprima.js:5689:23)
    at Object.Instrumenter.instrumentSync (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/lib/instrumenter.js:457:27)
    at /Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/lib/command/common/run-with-cover.js:224:33
    at Array.forEach (native)
    at process.<anonymous> (/Users/Daniel/dev/node/eintrittskarten/node_modules/istanbul/lib/command/common/run-with-cover.js:222:39)
    at process.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at process.emit (events.js:182:7)
    at process.exit (internal/process.js:79:15)
    at done (/Users/Daniel/dev/node/eintrittskarten/node_modules/mocha/bin/_mocha:416:32)
    at afterWrite (_stream_writable.js:354:3)
    at _combinedTickCallback (internal/process/next_tick.js:80:20)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm ERR! Test failed.  See above for more details.
```

**Comment by danieldiekmeier** [comment]
Okay, this may have been related to ES6. I installed Istanbul@1.0.0-alpha.2 and it now works if I call it with babel-node.
