### ISSUE TITLE
does not work 

### ISSUE THREAD

**Issue by OleksandrGonchar** [gotwarlost/istanbul#664]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test:single' ]
2 info using npm@3.9.5
3 info using node@v6.2.2
4 verbose run-script [ 'pretest:single', 'test:single', 'posttest:single' ]
5 info lifecycle grow@1.1.0~pretest:single: grow@1.1.0
6 silly lifecycle grow@1.1.0~pretest:single: no script for pretest:single, continuing
7 info lifecycle grow@1.1.0~test:single: grow@1.1.0
8 verbose lifecycle grow@1.1.0~test:single: unsafe-perm in lifecycle true
9 verbose lifecycle grow@1.1.0~test:single: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\work\grow\node_modules\.bin;C:\Program Files\nodejs;C:\Users\Oleksandr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Oleksandr\bin;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Files\Android\Android Studio;C:\Users\Oleksandr\AppData\Local\Android\sdk;C:\Users\Oleksandr\AppData\Roaming\npm;C:\Program Files\Java\jdk1.7.0_79\bin;C:\Users\Oleksandr\AppData\Local\atom\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle grow@1.1.0~test:single: CWD: D:\work\grow
11 silly lifecycle grow@1.1.0~test:single: Args: [ '/d /s /c', 'istanbul cover src/index.test.js' ]
12 silly lifecycle grow@1.1.0~test:single: Returned: code: 1  signal: null
13 info lifecycle grow@1.1.0~test:single: Failed to exec test:single script
14 verbose stack Error: grow@1.1.0 test:single: `istanbul cover src/index.test.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid grow@1.1.0
16 verbose cwd D:\work\grow
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:single"
19 error node v6.2.2
20 error npm  v3.9.5
21 error code ELIFECYCLE
22 error grow@1.1.0 test:single: `istanbul cover src/index.test.js`
22 error Exit status 1
23 error Failed at the grow@1.1.0 test:single script 'istanbul cover src/index.test.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the grow package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     istanbul cover src/index.test.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs grow
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls grow
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by piuccio** [comment]
Not sure I understand the logs, but I might have the same problem.

Istanbul + karma used to work fine one node `6.1`, I've now upgraded to `6.3` and my tests are broken.

Tests pass if I disable istanbul

**Comment by piuccio** [comment]
Sorry turn out that my problem was coming from a weird combination of rollup plugins, for some reason the code to be instrumented ended up being different between node `6.1` and `6.3`, black magic...

Ignore me

**Comment by jcollum** [comment]
`Failed at the grow@1.1.0 test:single script 'istanbul cover src/index.test.js'.` 

Are you sure this isn't an issue with the `grow` project?
