### ISSUE TITLE
internal lib error

### ISSUE THREAD

**Issue by ORESoftware** [gotwarlost/istanbul#723]
Ok, I do think this is an internal library error, please see:
```

Error: Command failed: cd /Users/Olegzandr/WebstormProjects/oresoftware/suman && istanbul report --dir /Users/Olegzandr/WebstormProjects/oresoftware/suman/coverage --include **/*coverage.json lcov
/usr/local/lib/node_modules/istanbul/lib/object-utils.js:59
                var line = statementMap[st].start.line,
                                           ^

TypeError: Cannot read property 'start' of undefined
    at /usr/local/lib/node_modules/istanbul/lib/object-utils.js:59:44
    at Array.forEach (native)
    at Object.addDerivedInfoForFile (/usr/local/lib/node_modules/istanbul/lib/object-utils.js:58:37)
    at Collector.fileCoverageFor (/usr/local/lib/node_modules/istanbul/lib/collector.js:94:15)
    at /usr/local/lib/node_modules/istanbul/lib/report/html.js:558:90
    at Array.forEach (native)
    at HtmlReport.writeReport (/usr/local/lib/node_modules/istanbul/lib/report/html.js:557:27)
```

**Comment by ORESoftware** [comment]
e.g. =>


![screenshot 2016-11-08 13 04 51](https://cloud.githubusercontent.com/assets/11139560/20117106/fc1d2c00-a5b3-11e6-92ee-54ad03db9d4e.png)
