### ISSUE TITLE
No such file or directory (istanbul-reports/lib/html/assets)

### ISSUE THREAD

**Issue by loick** [gotwarlost/istanbul#743]
[Bug] 

Hi there, when I'm using the test-coverage of Jest (so basically Istanbul), I get this error stack: 

```
Failed to write coverage reports:
        ERROR: Error: ENOENT: no such file or directory, scandir '{path}/node_modules/istanbul-reports/lib/html/assets'
        STACK: Error: ENOENT: no such file or directory, scandir '{path}/node_modules/istanbul-reports/lib/html/assets'
    at Object.fs.readdirSync (fs.js:870:18)
    at copyAssets ({path}/node_modules/istanbul-reports/lib/html/index.js:156:16)
    at {path}/node_modules/istanbul-reports/lib/html/index.js:173:9
    at Array.forEach (native)
    at HtmlReport.onStart ({path}/node_modules/istanbul-reports/lib/html/index.js:172:21)
    at LcovReport.(anonymous function) [as onStart] ({path}/node_modules/istanbul-reports/lib/lcov/index.js:24:24)
    at Visitor.(anonymous function) [as onStart] ({path}/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at Tree.visit ({path}/node_modules/istanbul-lib-report/lib/tree.js:157:13)
    at {path}/kirk/node_modules/istanbul-api/lib/reporter.js:84:18
    at Array.forEach (native)
```

I can see there are no file or directory named `assets` in the html folder, do you know why ? 

I'm using Jest v18.1.0.

**Comment by Uepsilon** [comment]
I've got the same issue when using karma instead of jest. 

Stack:
webpack@2.2.0.rc-3
karma@1.3.0
babel-istanbul@0.6.1

**Comment by martijnsenden** [comment]
Same here.

Stack:
webpack@2.2.0-rc.3
jest@17.0.2
istanbul@0.4.5
istanbul-reports@1.0.0
istanbul-api@1.1.0
babel-plugin-istanbul@2.0.3

**Comment by noxxious** [comment]
Had the same issue, but only after I ran the yarn clean. Removing .yarnclean file and reinstalling all modules fixed the issue.

**Comment by rstuven** [comment]
Yes, that worked!
`
rm -rf node_modules .yarnclean && yarn
`

**Comment by pelle** [comment]
Why would istanbul need to write in the node_modules directory? That seems wrong.

**Comment by rstuven** [comment]
@pelle It's trying to read the templates in node_modules. Maybe a better message would be "Failed to create coverage reports", because at that point it is not writing anything.

**Comment by rlecaro2** [comment]
As referenced [here](https://github.com/jmcriffey/babel-istanbul/issues/78) and [here](https://github.com/yarnpkg/yarn/issues/1235) yarn is cleaning the `assets` folders in `node_modules`.

I just ignored the necessary folders inside the .yarnclean file (so it still cleans everything else).

```
# asset directories
docs
doc
website
images
!istanbul-reports/lib/html/assets
```
Note the `!` sign

**Comment by morphatic** [comment]
I like the solution @rlecaro2 suggested. FYI, his pattern didn't work for me. Instead I had to use:

```
# asset directories
!nyc/node_modules/istanbul-reports/lib/html/assets
```

Thanks!

**Comment by jmjpro** [comment]
Thanks @rlecaro2. For me the pattern was !istanbul/lib/assets

**Comment by BeatriceThalo** [comment]
after editing .yarnclean per @jmjpro , removing node_modules, and a fresh `yarn install`, I am getting "Error: File not found with singular glob: project-root/coverage/coverage-final.json" which must relate to @rstuven 's reasoning.

**Comment by danieltwork** [comment]
At the moment, an exception to two places should be added.

.yarnclean file: 

`
# asset directories
docs
doc
website
images
assets
!istanbul-reports/lib/html/assets
!istanbul-api/node_modules/istanbul-reports/lib/html/assets
`

**Comment by danieltwork** [comment]
> Yes, that worked!
> `rm -rf node_modules .yarnclean && yarn`

The .yarnclean file is used to clean folders depending on the files you do not need, it is better is to control what should be removed, if you use istanbul-reports, you should add an exception to the .yarnclean file so that you do not delete the assets folder in this dependence.
