### ISSUE TITLE
No coverage information was collected, exit without writing coverage information

### ISSUE THREAD

**Issue by smart09091** [gotwarlost/istanbul#750]
I tried to use istanbul with _mocha and got this error

No coverage information was collected, exit without writing coverage information
C:\Users\Adrian\AppData\Roaming\npm\_mocha.cmd:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^
SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\Adrian\AppData\Roaming\npm\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at runFn (C:\Users\Adrian\AppData\Roaming\npm\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
    at C:\Users\Adrian\AppData\Roaming\npm\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17

testing using only mocha didnt have any errors can anyone help me with this?

**Comment by spawnrider** [comment]
See this issue : https://github.com/gotwarlost/istanbul/issues/90
