### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by patrikx3** [gotwarlost/istanbul#802]
i am creating a simple function, why it says ```ReferenceError: document is not defined``` ?
What should i do?
Istanbul doesnt recognize ```document``` and ```window``` ?

**Comment by patrikx3** [comment]
No idea to fix it. Please let me know, why in line 1??? No Document in it.
```bash
/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/src/config/webpack/plugin/html-preloader/html-preloader.js:1
(function (exports, require, module, __filename, __dirname) { var cov_19ny1ni1zq=function(){var path='/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/src/config/webpack/plugin/html-preloader/html-preloader.js',hash='4865950a9a3b300cdaee6c36730486cac2d67b71',global=new Function('return this')(),gcv='$$cov_1492277232488$$',coverageData={path:'/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/src/config/webpack/plugin/html-preloader/html-preloader.js',statementMap:{'0':{start:{line:1,column:0},end:{line:151,column:5}},'1':{start:{line:7,column:4},end:{line:7,column:21}},'2':{start:{line:9,column:19},end:{line:9,column:42}},'3':{start:{line:10,column:22},end:{line:10,column:48}},'4':{start:{line:11,column:16},end:{line:11,column:44}},'5':{start:{line:12,column:19},end:{line:12,column:21}},'6':{start:{line:13,column:23},end:{line:13,column:25}},'7':{s

ReferenceError: window is not defined
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/src/config/webpack/plugin/html-preloader/html-preloader.js:1:13778
    at Object.<anonymous> (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/src/config/webpack/plugin/html-preloader/html-preloader.js:2:6629)
    at Module._compile (module.js:571:32)
    at Module.replacementCompile (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (module.js:580:10)
    at Object.<anonymous> (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/node_modules/mocha/bin/_mocha:459:18)
    at Module._compile (module.js:571:32)
    at Module.replacementCompile (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (module.js:580:10)
    at Object.<anonymous> (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
    at runFn (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/node_modules/istanbul/lib/command/cover.js:126:16)
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/node_modules/istanbul/lib/command/cover.js:146:9
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/node_modules/istanbul-api/lib/run-cover.js:187:16
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/node_modules/istanbul-api/lib/file-matcher.js:69:16
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/node_modules/istanbul-api/node_modules/async/dist/async.js:1110:9
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/node_modules/istanbul-api/node_modules/async/dist/async.js:460:16
    at iteratorCallback (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/node_modules/istanbul-api/node_modules/async/dist/async.js:1034:13)
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/node_modules/istanbul-api/node_modules/async/dist/async.js:944:16
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular/node_modules/istanbul-api/node_modules/async/dist/async.js:1107:13
    at LOOP (fs.js:1718:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
