### ISSUE TITLE
/* istanbul ignore next */

### ISSUE THREAD

**Issue by patrikx3** [gotwarlost/istanbul#803]
Ciao! Hi! Hello!

I use the exact required comment: 
```js
/* istanbul ignore next */
```
Still I get an error:
```TypeError: Cannot read property 'loadLibSync' of undefined```, but i am saying already to ignore. It looks like it is ignoring my comments!

Though, in the console, it prints the coverage!
So weird, I cannot fix it. 
If i remove the line, it works!

**Comment by patrikx3** [comment]
Error: 
```bash
=============================== Coverage summary ===============================
Statements   : 19.36% ( 140/723 )
Branches     : 2.43% ( 6/247 )
Functions    : 0% ( 0/99 )
Lines        : 19.47% ( 140/719 )
================================================================================
/home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/src/service/express/index.js:11
++cov_1mjem6n9m1.s[69];projectAppRoutePathRouterItemChild.handle=asyncHandleDecorator;});});++cov_1mjem6n9m1.s[70];app.use(`/api/${project}`,projectApp);}}++cov_1mjem6n9m1.s[71];this.stats={routes:registryRoutes};++cov_1mjem6n9m1.s[72];app.all('**',(req,res)=>{++cov_1mjem6n9m1.f[5];++cov_1mjem6n9m1.s[73];return res.notFound();});let resolver,rejecter;++cov_1mjem6n9m1.s[74];app.listen(settings.port,()=>{++cov_1mjem6n9m1.f[6];++cov_1mjem6n9m1.s[75];console.info(`${service.prefix} ready`);++cov_1mjem6n9m1.s[76];resolver();});++cov_1mjem6n9m1.s[77];return new Promise((resolve,reject)=>{++cov_1mjem6n9m1.f[7];++cov_1mjem6n9m1.s[78];resolver=resolve;++cov_1mjem6n9m1.s[79];rejecter=reject;});};};++cov_1mjem6n9m1.s[80];service.wants=['mongoose','redis','phantom','session'];++cov_1mjem6n9m1.s[81];service.alias='express';/* istanbul ignore next */service.decorator=corifeus.core.loader.loadLibSync(`${__dirname}/decorator`);/* ista

TypeError: Cannot read property 'loadLibSync' of undefined
    at Object.<anonymous> (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/src/service/express/index.js:11:887)
    at Module._compile (module.js:571:32)
    at Module.replacementCompile (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (module.js:580:10)
    at Object.<anonymous> (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/node_modules/mocha/bin/_mocha:459:18)
    at Module._compile (module.js:571:32)
    at Module.replacementCompile (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (module.js:580:10)
    at Object.<anonymous> (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
    at runFn (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/node_modules/istanbul/lib/command/cover.js:126:16)
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/node_modules/istanbul/lib/command/cover.js:146:9
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/node_modules/istanbul-api/lib/run-cover.js:187:16
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/node_modules/istanbul-api/lib/file-matcher.js:69:16
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/node_modules/istanbul-api/node_modules/async/dist/async.js:1013:9
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/node_modules/istanbul-api/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/node_modules/istanbul-api/node_modules/async/dist/async.js:936:13)
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/node_modules/istanbul-api/node_modules/async/dist/async.js:840:16
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-server/node_modules/istanbul-api/node_modules/async/dist/async.js:1010:13
    at LOOP (fs.js:1718:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
>> 
Warning: Task "mocha_istanbul:cory-coverage" failed. Use --force to continue.

```
