### ISSUE TITLE
Unexpected token with node magic syntax

### ISSUE THREAD

**Issue by edpop** [gotwarlost/istanbul#827]
### Reproducing

1. Files
```js
// test/test.js
const assert = require('assert');

let {a:b = null} = {a: 'hello'};

console.log('Here is OK');
assert(b === 'hello');

require('../modules/module');
```

```js
// modules/module.js
console.log('Here is FAIL');
let {a:b = null} = {a: 'hello'};
```

2. npm scripts
```json
{
  "coverage": "istanbul cover _mocha -- -R spec",
  "test": "mocha"
}
```

`npm test` works fine, but `npm run coverage` fails with
```
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/%USERNAME%/mocha_test/node_modules/istanbul/lib/hook.js:107:24)
......
```
If I comment `let {a:b = null} = {a: 'hello'};` in module.js, then it will be OK.

I hate this syntax, but it works in real life outside of istanbul.

### ENV
node: 6.9.1
npm: 3.10.8
istanbul: 0.4.5
mocha: 3.4.2

**Comment by edpop** [comment]
Fixed in nyc
