### ISSUE TITLE
ES6 Arrow functions unexpected token?

### ISSUE THREAD

**Issue by elias-garcia** [gotwarlost/istanbul#841]
Hi, I'm using the latest version of Istanbul with the latest version of Mocha. I'm trying to test this code:

```
const validator = require('validator');
const User = require('../user/user.model');
const sessionService = require('./session.service');
const ApiError = require('../api-error');
const json = require('../../util/json');

const logIn = async (req, res, next) => {
  try {
    /**
     * Validate the body params
     */
    if (typeof (req.body.email) !== 'string' ||
      !validator.isEmail(req.body.email)) {
      throw new ApiError(400, 'bad request');
    }

    /**
     * Log in the user into the application
     */
    const session = await sessionService.logIn(req.body.email, String(req.body.password));

    /**
     * Return the session object
     */
    return res.status(200).json(json.createData('session', session));
  } catch (err) {
    return next(err);
  }
};

module.exports = {
  logIn
};

```

Then I run my tests with this script: `./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha ./src/**/*.test.js --report html -- -R spec`. It fails with this stacktrace:

```
MacBook-Pro-de-Elias:sporter-api elias$ npm run cover

> sporter-api@1.0.0 cover /Users/elias/Documents/tfg/sporter-app/sporter-api
> istanbul cover ./node_modules/mocha/bin/_mocha ./src/**/*.test.js --report html -- -R spec

Failed to parse file: /Users/elias/Documents/tfg/sporter-app/sporter-api/src/api/session/session.controller.js
Transformation error; return original code
{ Error: Line 7: Unexpected token =>
    at constructError (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:2407:21)
    at createError (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:2500:13)
    at throwUnexpectedToken (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:2505:15)
    at consumeSemicolon (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:2620:13)
    at parseLexicalDeclaration (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:4183:9)
    at parseStatementListItem (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3977:24)
    at parseFunctionSourceElements (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:4869:23)
    at parseFunctionExpression (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:5074:16)
    at parsePrimaryExpression (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3273:24)
    at inheritCoverGrammar (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:2681:18)
    at parseLeftHandSideExpressionAllowCall (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3414:20)
    at inheritCoverGrammar (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:2681:18)
    at parsePostfixExpression (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3490:16)
    at parseUnaryExpression (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3550:20)
    at inheritCoverGrammar (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:2681:18)
    at parseBinaryExpression (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3639:16)
    at inheritCoverGrammar (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:2681:18)
    at parseConditionalExpression (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3696:16)
    at parseAssignmentExpression (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3893:16)
    at inheritCoverGrammar (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:2681:18)
    at parseGroupExpression (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3162:16)
    at inheritCoverGrammar (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:2681:18)
    at parsePrimaryExpression (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3239:20)
    at inheritCoverGrammar (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:2681:18)
    at parseLeftHandSideExpressionAllowCall (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3414:20)
    at inheritCoverGrammar (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:2681:18)
    at parsePostfixExpression (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3490:16)
    at parseUnaryExpression (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3550:20)
    at inheritCoverGrammar (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:2681:18)
    at parseBinaryExpression (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3639:16)
    at inheritCoverGrammar (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:2681:18)
    at parseConditionalExpression (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3696:16)
    at parseAssignmentExpression (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3893:16)
    at isolateCoverGrammar (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:2663:18)
    at parseExpression (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3942:16)
    at parseExpressionStatement (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:4222:20)
    at parseStatement (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:4760:24)
    at parseStatementListItem (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:3989:16)
    at parseScriptBody (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:5490:25)
    at parseProgram (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:5506:16)
    at Object.parse (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/esprima/esprima.js:5690:23)
    at Instrumenter.instrumentSync (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/lib/instrumenter.js:459:31)
    at /Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/lib/hook.js:54:31
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/lib/hook.js:105:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/elias/Documents/tfg/sporter-app/sporter-api/src/api/session/session.routes.js:9:142)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/lib/hook.js:107:24)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/elias/Documents/tfg/sporter-app/sporter-api/src/api/index.js:9:138)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/lib/hook.js:107:24)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/elias/Documents/tfg/sporter-app/sporter-api/src/config/express.config.js:9:356)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/lib/hook.js:107:24)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/elias/Documents/tfg/sporter-app/sporter-api/src/config/index.js:9:59)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/lib/hook.js:107:24)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/elias/Documents/tfg/sporter-app/sporter-api/src/app.js:9:123)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/lib/hook.js:107:24)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/elias/Documents/tfg/sporter-app/sporter-api/src/api/session/session.test.js:9:188)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/lib/hook.js:107:24)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
    at runFn (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at /Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at /Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at /Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/node_modules/async/lib/async.js:361:13
    at /Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at done (/Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/node_modules/async/lib/async.js:246:17)
    at /Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/node_modules/async/lib/async.js:44:16
    at /Users/elias/Documents/tfg/sporter-app/sporter-api/node_modules/istanbul/node_modules/async/lib/async.js:358:17
    at LOOP (fs.js:1716:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9) lineNumber: 7, description: 'Unexpected token =>', index: 273 }
```

All the tests are passing, but before they runs I'm getting this error. I get this error for every file with arrow functions. Any idea on what's happening with Esprima? Is the version used in Instanbul compatible with Arrow functions? Thanks.

**Comment by mscottx88** [comment]
I am seeing this same error.  Any updates?

**Comment by elias-garcia** [comment]
Hi @mscottx88 , I was searching a lot about the issue and it's gone if you update the istanbul version in your package.json to alpha.2 version... The error is gone and no issues with the alpha, so this is the best workaround...  In your package.json: `"istanbul": "^1.0.0-alpha.2"`.

**Comment by bdushimi** [comment]
Thanks @elias-garcia, it works

**Comment by chrisdothtml** [comment]
Is there any way to fix/workaround this without switching to a two-year-old alpha?
