### ISSUE TITLE
Coverage Invalid report format [html]

### ISSUE THREAD

**Issue by rmartin94** [gotwarlost/istanbul#884]
Hi! I've been using karma and istanbul for quite a while. Been running some unit tests for my angular app, and now while trying to get the coverage for my test I run

` ng test --code-coverage`

and I'm getting the following error

`29 05 2018 10:32:56.941:ERROR [karma]: { Error: Invalid report format [html]
    at Object.module.exports.create (D:\SDPWebDevGit\node_modules\istanbul-api\lib\input-error.js:6:15)
    at Reporter.add (D:\SDPWebDevGit\node_modules\istanbul-api\lib\reporter.js:51:30)
    at D:\SDPWebDevGit\node_modules\istanbul-api\lib\reporter.js:62:18
    at Array.forEach (<anonymous>)
    at Reporter.addAll (D:\SDPWebDevGit\node_modules\istanbul-api\lib\reporter.js:61:14)
    at createReport (D:\SDPWebDevGit\node_modules\karma-coverage-istanbul-reporter\src\reporter.js:83:14)
    at browsers.forEach.browser (D:\SDPWebDevGit\node_modules\karma-coverage-istanbul-reporter\src\reporter.js:196:9)
    at Array.forEach (<anonymous>)
    at Collection.forEach (D:\SDPWebDevGit\node_modules\karma\lib\browser_collection.js:93:21)
    at CoverageIstanbulReporter.onRunComplete (D:\SDPWebDevGit\node_modules\karma-coverage-istanbul-reporter\src\reporter.js:195:16)
    at Server.<anonymous> (D:\SDPWebDevGit\node_modules\karma\lib\events.js:13:22)
    at emitTwo (events.js:131:20)
    at Server.emit (events.js:214:7)
    at Timeout._onTimeout (D:\SDPWebDevGit\node_modules\karma\lib\executor.js:51:17)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) inputError: true }`

This seems quite strange to me, it was working fine before, I haven't updated any node package. Tried cleanning cache, deleting the coverage folder with my previous results but no luck. Then I removed my karma and istanbul nodemodules and installed them again but this error persists. Been looking arround for a solution of if its a common problem but I didn't found anything.

Does someone stumbled with this? Thanks for any info or help!

**Comment by oleg-koval** [comment]
I have the same, already spent some hours debugging, but no luck

**Comment by kievsash** [comment]
Had this issue, but somehow removing node_modules and making npm install again solved this.
