### ISSUE TITLE
Error on html report generation

### ISSUE THREAD

**Issue by evil-shrike** [gotwarlost/istanbul#94]
I have a coverage.json file with coverage info extracted from within browser after qunit tests completed (as value of window.**coverage**). No I'm trying to generate a html report:

Then I execute:

``` shell
istanbul report html coverage.json 
```

and get the following error:

```
C:\...\Client\node_modules\istanbul\lib\report\html.js:156
        structuredText[lineNumber].covered = count > 0 ? 'yes' : 'no';
                                                 ^
TypeError: Cannot set property 'covered' of undefined
    at C:\...\Client\node_modules\istanbul\lib\report\html.js:156:66
    at Array.forEach (native)
    at annotateLines (C:\...\Client\node_modules\istanbul\lib\report\html.js:154:28)
    at HtmlReport.Report.mix.writeDetailPage (C:\...\Client\node_modules\istanbul\lib\report\html.js:370:9)
    at C:\...\Client\node_modules\istanbul\lib\report\html.js:435:26
    at AsyncFileWriter.extend.processFile (C:\...\Client\node_modules\istanbul\lib\util\file-writer.js:93:9)
    at Object.q.process [as _onImmediate] (C:\...\Client\node_modules\istanbul\node_modules\async\lib\async.js:728:21)
    at processImmediate [as _immediateCallback] (timers.js:317:15)
```

"text" report generation works.

**Comment by SarahFowler73** [comment]
Using mochify-istanbul, I found that anything that I was using transform for would mess up the source mapping. Adding exclude['**/*.html', '**/*.css', and '**.*.json'] completely cleared up the problem for me.
